name: tikitar_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # flutter_svg: ^2.0.17  # not using, rather remove or use it
  shared_preferences: ^2.2.2 #using it to store the data in the device
  http: ^1.3.0 #to make the http requests from the application
  flutter_inappwebview: ^6.1.5 #to show the web pages in the device
  flutter_html: ^3.0.0-alpha.6
  permission_handler: ^12.0.0+1 #to check and allow for the permissions
  geolocator: ^14.0.2 #to access the location of the user
  file_picker: ^10.1.2 #to allow the user to pick the files
  image_picker: ^1.1.2 #to allow the user to pick the images
  qr_flutter: ^4.1.0 #to create the qr-code for the contact card of the user
  flutter_svg: ^2.1.0 #to use the svg pictures inside the application
  sqflite: ^2.4.2
  path: ^1.9.1 
  path_provider: ^2.1.5
  url_launcher: ^6.3.1 #to open the url into the browser
  firebase_messaging: ^15.2.6 #needed for notificaitons in android
  flutter_local_notifications: ^19.2.1 #
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6 #for analytics
  get: ^4.7.2 #to manage the routes of the application
  flutter_background_service: ^5.1.0
  clarity_flutter: ^1.0.0 #to track the usage and other data
  flutter_riverpod: ^2.6.1 #the state managment library, used in application

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 #to create the launching icon for the app
  flutter_native_splash: ^2.4.6 #to create the splash screen for the app
  change_app_package_name: ^1.5.0 #allowed to change the package name for the application
  custom_lint: ^0.8.0

flutter_native_splash:
  color: "#ffffff"                        # background color
  image: assets/images/app-icon.png    # path to your logo
  android: true
  ios: true
  fullscreen: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tikitar-logo.png"  # Replace with your icon path
  adaptive_icon_background: "#ffffff"  # Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/icon/tikitar-logo.png"  # Foreground image for adaptive icons

flutter:
  uses-material-design: true

  # Add the assets section here
  assets:
    - assets/images/