const String baseUrl = "https://app.tikitar.com/app_webview/dev/";

final statesData = [
  "Arunachal Pradesh",
  "Himachal Pradesh",
  "Madhya Pradesh",
  "Maharashtra",
  "Puducherry",
  "Uttar Pradesh",
  "Chhattisgarh",
  "Jharkhand",
  "Meghalaya",
  "Punjab",
  "Tripura",
  "Bihar",
  "Delhi",
  "Kerala",
  "Sikkim",
  "The Dadra And Nagar Haveli And Daman And Diu",
  "Uttarakhand",
  "Andaman And Nicobar Islands",
  "Andhra Pradesh",
  "Assam",
  "Chandigarh",
  "Haryana",
  "Jammu And Kashmir",
  "Ladakh",
  "Mizoram",
  "Odisha",
  "Telangana",
  "Goa",
  "Gujarat",
  "Karnataka",
  "Lakshadweep",
  "Manipur",
  "Nagaland",
  "Rajasthan",
  "Tamil Nadu",
  "West Bengal"
];
